In [3]:
import numpy as np
import cv2

In [4]:
img = cv2.imread('./images/messi.jpg') #BGR

In [5]:
print(img)

[[[115 108 129]
  [113 106 127]
  [109 102 123]
  ...
  [147 122 112]
  [143 121 110]
  [148 126 120]]

 [[115 108 129]
  [113 106 127]
  [109 102 123]
  ...
  [146 121 111]
  [142 120 109]
  [147 125 119]]

 [[111 107 126]
  [110 106 125]
  [107 103 122]
  ...
  [143 121 110]
  [141 119 108]
  [145 123 117]]

 ...

 [[ 76  50  68]
  [ 75  49  67]
  [ 72  48  66]
  ...
  [ 67  47  36]
  [ 67  47  36]
  [ 63  42  34]]

 [[ 80  54  72]
  [ 79  53  71]
  [ 77  51  69]
  ...
  [ 66  46  35]
  [ 68  46  35]
  [ 62  41  33]]

 [[ 84  58  76]
  [ 82  56  74]
  [ 80  54  72]
  ...
  [ 67  45  34]
  [ 68  46  35]
  [ 62  41  33]]]


In [7]:
(b,g,r) = img[0,1] 
print("blue : {}, green : {} , red : {}".format(b,g,r))

blue : 113, green : 106 , red : 127


In [8]:
img.max()

255

In [9]:
img.min()

0

In [10]:
img.shape

(262, 193, 3)

In [11]:
262*193

50566

In [12]:
cv2.imshow('Messi', img)
cv2.waitKey(0)
cv2.destroyAllWindows()